install.packages("ggplot2")
library(ggplot2)
library(corrplot)
library(datasets)
library(tidyverse)
library(psych)
library(tidyr)
c<-read.csv("imports-85.data")
names(c)[1]<-"symboling"
names(c)[2]<-"normalized_losses"
names(c)[3]<-"make"
names(c)[4]<-"fuel_type"
names(c)[5]<-"aspiration"
names(c)[6]<-"num_of_doors"
names(c)[7]<-"body_style"
names(c)[8]<-"drive_wheels"
names(c)[9]<-"engine_location"
names(c)[10]<-"wheel_base"
names(c)[11]<-"length"
names(c)[12]<-"width"
names(c)[13]<-"height"
names(c)[14]<-"curb_weight"
names(c)[15]<-"engine_type"
names(c)[16]<-"num_of_cylinders"
names(c)[17]<-"engine_size"
names(c)[18]<-"fuel_system"
names(c)[19]<-"bore"
names(c)[20]<-"stroke"
names(c)[21]<-"compression_ratio"
names(c)[22]<-"horsepower"
names(c)[23]<-"peak_rpm"
names(c)[24]<-"city_mpg"
names(c)[25]<-"highway_mpg"
names(c)[26]<-"price"
describe(c,na.rm=TRUE,skew=FALSE)
sapply(c,class)
cc<-subset(c, select = c("length","width","height","curb_weight","engine_size","compression_ratio","city_mpg","highway_mpg","price")) 
car<-na.omit(c)
car
cor(cc,cc)
is.na(cc)
dc<-c[rowSums(is.na(c))==0]
ggph<-ggplot(cc,aes("length","width"))
geom_tile(aes(fill=value))
ggph
